//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

// <auto-generated />
public partial class Pages_BookingDetails
{

    protected global::System.Web.UI.WebControls.Label lblError;

    protected global::System.Web.UI.WebControls.Literal litBookingId;
    protected global::System.Web.UI.WebControls.Literal litStatus;

    protected global::System.Web.UI.WebControls.Literal litGuestName;
    protected global::System.Web.UI.WebControls.Literal litGuestEmail;
    protected global::System.Web.UI.WebControls.Literal litPhone;

    protected global::System.Web.UI.WebControls.Literal litRoom;
    protected global::System.Web.UI.WebControls.Literal litDates;
    protected global::System.Web.UI.WebControls.Literal litNightly;
    protected global::System.Web.UI.WebControls.Literal litTotal;
    protected global::System.Web.UI.WebControls.Literal litServices;

    protected global::System.Web.UI.WebControls.Panel pnlGuestActions;
    protected global::System.Web.UI.WebControls.Button btnCancel;
    protected global::System.Web.UI.WebControls.Label lblCancelResult;

    protected global::System.Web.UI.WebControls.Panel pnlAdmin;
    protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
    protected global::System.Web.UI.WebControls.Button btnUpdateStatus;
    protected global::System.Web.UI.WebControls.TextBox txtComment;
    protected global::System.Web.UI.WebControls.Button btnAddComment;
    protected global::System.Web.UI.WebControls.BulletedList bltComments;
}
