//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_CreateBooking
{
    /// <summary>
    /// lblMsg control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblMsg;

    /// <summary>
    /// txtName control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtName;

    /// <summary>
    /// txtPhone control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtPhone;

    /// <summary>
    /// ddlRoom control.
    /// </summary>
    protected global::System.Web.UI.WebControls.DropDownList ddlRoom;

    /// <summary>
    /// txtCheckIn control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtCheckIn;

    /// <summary>
    /// txtCheckOut control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtCheckOut;

    /// <summary>
    /// cblServices control.
    /// </summary>
    protected global::System.Web.UI.WebControls.CheckBoxList cblServices;

    /// <summary>
    /// btnCreate control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnCreate;
}
