//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_RoomManagement
{
    /// <summary>
    /// lblMsg control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblMsg;

    /// <summary>
    /// txtRoomId control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtRoomId;

    /// <summary>
    /// ddlType control.
    /// </summary>
    protected global::System.Web.UI.WebControls.DropDownList ddlType;

    /// <summary>
    /// chkAvailable control.
    /// </summary>
    protected global::System.Web.UI.WebControls.CheckBox chkAvailable;

    /// <summary>
    /// txtNotes control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtNotes;

    /// <summary>
    /// btnAdd control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnAdd;

    /// <summary>
    /// btnUpdate control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnUpdate;

    /// <summary>
    /// btnDelete control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnDelete;

    /// <summary>
    /// rptRooms control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Repeater rptRooms;
}
